name: aim-multiverse-web
services:
- name: web
  source_dir: /
  github:
    repo: your-username/aim-multiverse-web
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
